import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

// @ts-expect-error TS2345: Argument of type '{ build: typeof build; }' is not assignable to parameter of type 'PagesFunctionHandlerOptions<Env, unknown>'.
export const onRequest = createPagesFunctionHandler({ build });
