import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";


// @ts-expect-error TS2322: Type 'typeof import("x:/Documents/GitHub/tabvar/build/server/index")' is not assignable to type 'ServerBuild | (() => ServerBuild | Promise<ServerBuild>)'.
export const onRequest = createPagesFunctionHandler({ build });
