import { createPagesFunctionHandler } from "@react-router/cloudflare";
import { RouterContextProvider } from "react-router";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `react-router build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";


export const onRequest = createPagesFunctionHandler({
  build: build as any,
  getLoadContext({ context }) {
    const routerContext = new RouterContextProvider();
    Object.assign(routerContext, { cloudflare: context.cloudflare });
    return routerContext;
  },
});
