// Generated by Wrangler on Mon Jul 01 2024 12:29:04 GMT-0600 (Mountain Daylight Saving Time)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	BASE_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	R2_ENDPOINT_URL: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ACCESS_KEY_ID: string;
	R2_TOKEN_VALUE: string;
	SLOPER_ID: string;
	SLOPER_P: string;
	SLOPER_URL: string;
	R2_BUCKET_DOMAIN: string;
	DB: D1Database;
}
