// Generated by Wrangler on Sat May 25 2024 00:27:54 GMT-0600 (Mountain Daylight Saving Time)
// by running `wrangler types`

interface Env {
	BASE_URL: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	R2_ENDPOINT_URL: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ACCESS_KEY_ID: string;
	R2_TOKEN_VALUE: string;
	TABVAR_ISSUES_UPLOADS: R2Bucket;
	DB: D1Database;
}
