import { Text, Typography } from "@mantine/core";
import sanitizeHtml from "sanitize-html";

interface RichTextViewerProps {
  content: string;
  // We can add more props here later if needed (e.g., custom classNames, styles)
}

const HTML_TAG_REGEX = /<[a-z][\s\S]*>/i;

// Keep this limited to formatting supported by the editor and existing notes.
// In particular, no styles, event handlers, images, SVG, or embedded content.
const RICH_TEXT_OPTIONS = {
  allowedTags: ["p", "br", "h3", "strong", "b", "em", "i", "u", "s", "ul", "ol", "li", "blockquote", "a"],
  allowedAttributes: { a: ["href"] },
  allowedSchemes: ["http", "https", "mailto"],
  allowProtocolRelative: false,
};

/**
 * Renders HTML content generated by a rich text editor (like Tiptap)
 * using Mantine's TypographyStylesProvider for consistent styling.
 */
export function RichTextViewer({ content }: RichTextViewerProps) {
  // Return null or an empty fragment if content is empty/nullish
  // to avoid rendering an empty div.
  if (!content) {
    return null;
  }

  // Check if the content likely contains HTML tags
  const isHtml = HTML_TAG_REGEX.test(content);

  if (isHtml) {
    const safeHtml = sanitizeHtml(content, RICH_TEXT_OPTIONS);
    // Render as HTML using TypographyStylesProvider
    return (
      <Typography>
        <div dangerouslySetInnerHTML={{ __html: safeHtml }} />
      </Typography>
    );
  } else {
    // Render as plain text, preserving line breaks and wrapping
    return (
      <Text style={{ whiteSpace: 'pre-wrap', fontSize: 'var(--mantine-font-size-sm)' }}>
        {content}
      </Text>
    );
  }
}
